-- MySQL Script generated by MySQL Workbench
-- Thu Jul 23 14:06:18 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BusDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BusDB` ;

-- -----------------------------------------------------
-- Schema BusDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BusDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BusDB` ;

-- -----------------------------------------------------
-- Table `BusDB`.`BusStop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BusDB`.`BusStop` ;

CREATE TABLE IF NOT EXISTS `BusDB`.`BusStop` (
  `BusStopID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Latitude` DECIMAL(9,6) NOT NULL,
  `Longitude` DECIMAL(9,6) NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Street` VARCHAR(45) NULL,
  `District` VARCHAR(45) NULL,
  `Type` ENUM('a', 'b') NULL,
  `DateCreated` DATETIME NULL,
  `DateUpdated` DATETIME NULL,
  PRIMARY KEY (`BusStopID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BusDB`.`BusRoute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BusDB`.`BusRoute` ;

CREATE TABLE IF NOT EXISTS `BusDB`.`BusRoute` (
  `BusRouteID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Code` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `DateUpdated` DATETIME NOT NULL,
  `DateCreated` DATETIME NOT NULL,
  PRIMARY KEY (`BusRouteID`),
  UNIQUE INDEX `Code_UNIQUE` (`Code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BusDB`.`BusOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BusDB`.`BusOrder` ;

CREATE TABLE IF NOT EXISTS `BusDB`.`BusOrder` (
  `BusOrderID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BusRouteID` INT UNSIGNED NOT NULL,
  `BusStopID` INT UNSIGNED NOT NULL,
  `Order` INT UNSIGNED NOT NULL,
  `DateCreated` DATETIME NOT NULL,
  `DateUpdated` DATETIME NOT NULL,
  PRIMARY KEY (`BusOrderID`),
  INDEX `fk_BusOrder_BusRoute_idx` (`BusRouteID` ASC),
  INDEX `fk_BusOrder_BusStop1_idx` (`BusStopID` ASC),
  CONSTRAINT `fk_BusOrder_BusRoute`
    FOREIGN KEY (`BusRouteID`)
    REFERENCES `BusDB`.`BusRoute` (`BusRouteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BusOrder_BusStop1`
    FOREIGN KEY (`BusStopID`)
    REFERENCES `BusDB`.`BusStop` (`BusStopID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BusDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BusDB`.`User` ;

CREATE TABLE IF NOT EXISTS `BusDB`.`User` (
  `UsernameID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` INT NOT NULL,
  `DateCreated` DATETIME NOT NULL,
  `DateUpdated` DATETIME NOT NULL,
  PRIMARY KEY (`UsernameID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
